apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: tcp80-443-foo
spec:
  ingress:
  - ports:
    - port: "80"
      protocol: TCP
    - port: "443"
      protocol: TCP
    from:
    - podSelector:
          matchLabels:
              app: foo
  podSelector:
      matchLabels:
          app: meh
