apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: tcp80-443-meh
spec:
  ingress:
  - ports:
    - port: "80"
      protocol: TCP
    - port: "443"
      protocol: TCP
  podSelector:
      matchLabels:
          app: meh
