---
ovn_kubernetes_info:
  install_path: /usr/bin
  # ovn-kubernetes build info
  git_url: https://github.com/openvswitch/ovn-kubernetes
  build_path: /tmp
  branch: master

ovn_kubernetes_binaries:
  - ovnkube
  - ovn-k8s-cni-overlay
  - ovn-kube-util
  - ovnkube.exe
  - ovn-k8s-cni-overlay.exe
